<?php

require_once dirname(__FILE__) . '/../../Diablo3/Hero.php';

/**
 * Test class for Hero.
 * Generated by PHPUnit on 2012-08-16 at 13:58:18.
 */
class HeroTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Hero
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Hero(BATTLENET_ID, HERO_ID);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testConstructExpectsParam()
    {
        $this->setExpectedException('InvalidArgumentException');
        $obj = new Hero('', '');
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetInfo().
     */
    public function testGetInfo()
    {
        // Remove the following lines when you implement this test.
        $this->assertNotEmpty($this->object->getInfo());
    }

}

?>
