<?php

require_once dirname(__FILE__) . '/../../Diablo3/Profile.php';

/**
 * Test class for Profile.
 * Generated by PHPUnit on 2012-08-16 at 12:22:44.
 */
class ProfileTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Profile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Profile(BATTLENET_ID);
    }

    public function testConstructExpectsParam()
    {
        $this->setExpectedException('InvalidArgumentException');
        $obj = new Profile('');
    }

    /**
     * @covers {className}::{origMethodName}
     */
    public function testGetHeroes()
    {
        // Remove the following lines when you implement this test.
        $this->assertNotEmpty($this->object->getHeroes());
        $this->assertInternalType('array', $this->object->getHeroes());
    }
}

?>
